AssimentMVSData/Models/FuncPersonService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssimentMVSData.Models
{
    public class FuncPersonService : IPesronService
    {
        PersonViewModel personViewModel = new PersonViewModel();

        private int idCount = 1;

        public FuncPersonService()
        {
            CreatePerson("Max",  "London",  0729998877 );
            CreatePerson("Lax", "Bondon", 0729998877);
        }

        public List<Person> AllPersons()
        {
            return personViewModel.persons;
        }

        public Person CreatePerson(string name,string city ,int phone )
        {
            Person person = new Person() { Id = idCount, Name = name, City = city, Phone = phone };
            idCount++;
            personViewModel.persons.Add(person);
            return person;
        }

        public List<Person> DeletePerson(int id)//för ta bort måste sktiva list istället annat namn
        {
            foreach (Person item in personViewModel.persons)
            {
                if (item.Id == id)
                {
                    personViewModel.persons.Remove(item);
                    break;
                }
            }
            return personViewModel.persons;
        }

        public Person FindPerson(int id)
        {
            foreach (Person item in personViewModel.persons)
            {
                if (item.Id == id)
                {
                    return item;
                }
            }
            return null;
        }

        public bool UpdatePerson(Person person)//måste finnas update method att byta namn
        {
            foreach (Person item in personViewModel.persons)
            {
                if (item.Id == person.Id)
                {
                    item.Name = person.Name;
                    item.City = person.City;
                    item.Phone = person.Phone;
                    return true;
                }
            }
            return false;
        }
    }
}

AssimentMVSData/Models/IPesronService.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssimentMVSData.Models
{
    public interface IPesronService
    {
        Person CreatePerson(string name, string city , int phone);

        List<Person> AllPersons();

        Person FindPerson(int id);

        List<Person> DeletePerson(int id);

        bool UpdatePerson(Person person);
    }
}

AssimentMVSData/Models/Person.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssimentMVSData.Models
{
    public class Person
    {
        public int? Id { get; set; }

        public string Name { get; set; }

        public string City { get; set; }

        public int Phone { get; set; }
    }
}

AssimentMVSData/Models/PersonViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace AssimentMVSData.Models
{
    public class PersonViewModel
    {
        public List<Person> persons = new List<Person>();

        public string Filter { get; set; }
    }
}

AssimentMVSData/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace AssimentMVSData.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

AssimentMVSData/Controllers/PersonController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using AssimentMVSData.Models;
using Microsoft.AspNetCore.Mvc;

namespace AssimentMVSData.Controllers
{
    public class PersonController : Controller
    {
        PersonViewModel personViewModel = new PersonViewModel();

        IPesronService _personService;//interface to indjection

        public PersonController(IPesronService personService)
        {
            _personService = personService;
        }

        public IActionResult Index()
        {
            personViewModel.persons = _personService.AllPersons();

            return View(personViewModel);
        }

        [HttpPost]
        public IActionResult CreatePerson(Person person)
        {
            if (ModelState.IsValid)
            {
                //måste visa ett person eftersom partial
                person = _personService.CreatePerson(person.Name, person.City, person.Phone);

                return PartialView("_Person", person);//måste visa ett person eftersom partial
            }

            return BadRequest();//det betyder lägg inget till
        }

        [HttpGet]
        public IActionResult DelPerson(int? id)
        {
            if (id != null)
            {
                _personService.DeletePerson((int)id);
            }

            return Content("");//bara rensa person o inget mer
            //return View("Index",_personService.AllPersons());
            //return RedirectToAction("Index");
        }

        public IActionResult Person(Person person)
        {
            var item = _personService.FindPerson((int)person.Id);
            if (item != null)
            {

                return PartialView("_Person", item);
            }
            return NotFound();
        }
        [HttpGet]
        public IActionResult Edit(Person person)
        {
            if (person.Id == null)
            {
                return NotFound();
            }
            var item = _personService.FindPerson((int)person.Id);//cför att byta namn måste method hitta person
            if (person == null)
            {
                return NotFound();
            }
            return PartialView("_Edit", item);
        }

        [HttpPost, ActionName("Edit")]
        public IActionResult EditComplete(Person person)
        {

            if (ModelState.IsValid)
            {
                _personService.UpdatePerson(person);
                return PartialView("_Person", person);

            }
            return PartialView("_Edit", person);//om engenting är ändrat måste stanna i Edit
        }

        public IActionResult Filter(string filter)
        {
            if (string.IsNullOrWhiteSpace(filter))
            {
                return PartialView("_List", _personService.AllPersons());

            }
            else
            {

                filter = filter.ToLower();
                var vm = new PersonViewModel();//måste kalla model 
                vm.persons = _personService.AllPersons().Where(p => p.Name.ToLower().Contains(filter) || p.City.ToLower().Contains(filter)).ToList();//tolist det är convert
                return PartialView("_List", vm);
            }
        }
    }
}

AssimentMVSData/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Index";
}

<h1>This is Home</h1>

AssimentMVSData/Views/Person/Index.cshtml
@model PersonViewModel
@{
    ViewData["Title"] = "Person Index";
}

<h1>Person of List</h1>

<div class="row">
    <div class="col-12">
        <div class="row">
            <div class="col">Name:<input type="text" id="createName" name="name"></div>
            <div class="col">City:<input type="text" id="createCity" name="city"></div>
            <div class="col">Phone:<input type="text" id="createPhone" name="phone"></div>
            <div class="col">
                <button class="btn btn-success" onclick="LinkCreate('@Url.Action("CreatePerson", "Person")')">
                    Create Person
                </button>
            </div>
        </div>
    </div>
</div>
<div class="row">
    <div class="col-12">
        <input type="text" name="filter" id="filterlist" placeholder="Search on Name or City" />
        <button onclick="LinkFilter('@Url.Action("Filter","Person")')">Search</button>
    </div>
</div>
<hr />
<div class="row">
    <div class="col"><b>Name</b></div>
    <div class="col"><b>City</b></div>
    <div class="col"><b>Telefon</b></div>
</div>
<hr />
<ul>  
        @await Html.PartialAsync("_List", Model)
</ul>

AssimentMVSData/Views/Person/_DelPerson.cshtml
@model Person

<div id="@("person" + Model.Id)">
    <form  method="post">
        <input type="hidden" name="Id" value="@Model.Id" />
        <input type="submit" onclick="@Url.Action("DelPerson","Person")" class="btn btn-danger" name="Id" value="Delete" />
    </form>
</div>

AssimentMVSData/Views/Person/_Edit.cshtml
@model Person


<div id="@("person" + Model.Id)" class="col-12">
    <dl class="dl-horizontal">
        <dt>Name</dt>
        <dd><input type="text" id="@("person" + Model.Id + "Name")" value="@Model.Name"></dd>
        <dt>City</dt>
        <dd><input type="text" id="@("person" + Model.Id + "City")" value="@Model.City"></dd>
        <dt>Phone</dt>
        <dd><input type="text" id="@("person" + Model.Id + "Phone")" value="@Model.Phone "></dd>
        <dt>
                                                    @* post                 post *@
            <button class="btn btn-success" onclick="LinkEdit('@Url.Action("Edit", "Person")' , '@("person" + Model.Id)' , '@Model.Id')">
                Save
            </button>
        </dt>
        <dd>
                                                                            @* iaction   controller          id*@
            <button class="btn btn-secondary" onclick="LinkUpdate('@Url.Action("Person", "Person", new { id = Model.Id })' , '@("person" + Model.Id)')">
                Back
            </button>
        </dd>
    </dl>
</div>

AssimentMVSData/Views/Person/_List.cshtml
@model PersonViewModel


<div class="row">
    <ul id="AllPersons">
        @foreach (var item in Model.persons)
        {
            @await Html.PartialAsync("_Person", item)
        }
    </ul>
</div>

AssimentMVSData/Views/Person/_Person.cshtml
@model Person

<div id="@("person" + Model.Id)" class="col-12 listrow">
    <div class="row">
        <div class="col">@Model.Name</div>
        <div class="col">@Model.City</div>
        <div class="col">@Model.Phone</div>
        <div class="col">
            <div class="row">
                <div class="col">                              @* get                  get *@
                    <button class="btn btn-warning" onclick="LinkUpdate('@Url.Action("Edit", "Person", new {id = Model.Id })' , '@("person" + Model.Id)')">
                        Edit
                    </button>
                </div>
                <div class="col">
                    <button class="btn btn-danger" onclick="LinkUpdate('@Url.Action("DelPerson", "Person", new { id = Model.Id })' , '@("person" + Model.Id)')">
                        Delete
                    </button>
                </div>
            </div>
        </div>
    </div>
</div>

AssimentMVSData/Views/Shared/_Layout.cshtml
<!DOCTYPE html>

<html>
<head>
    <meta name="viewport" content="width=device-width" />
    <title>@ViewBag.Title</title>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js"></script>

    <link href="~/CSS/StyleSheet.css" rel="stylesheet" />

    <script src="https://ajax.aspnetcdn.com/ajax/jQuery/jquery-3.3.1.min.js"></script>
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm bg-dark navbar-dark">

            <a class="navbar-brand" href="#"> @Html.ActionLink("Home", "Index", "Home")</a>

            <div class="collapse navbar-collapse" id="collapsibleNavbar">

                <ul class="navbar-nav">
                    <li class="nav-item">
                        <a asp-controller="Person" asp-action="Index">Person list</a>
                    </li>
                </ul>

            </div>

        </nav>

    </header>

    <div>
        @RenderBody()
    </div>
    <div>
        @*<a id="aUpdate" asp-controller="Person" asp-action="Person" asp-route-id="0" data-target="environment-container"> Update</a>
            <div id="environment-container"></div>*@ @*ajax smotret data-target*@
        </div>
        <footer>
            <p>Made by: Alhazur &copy; @DateTime.Now.ToString("yyyy")</p>
        </footer>
        <script>
            //Get
            function LinkUpdate(urlPath, targetUpdate) {
                console.log('LinkUpdate Url: ' + urlPath);
                console.log('Id Target: ' + targetUpdate);

                $.get(urlPath, function (res) {
                    $('#' + targetUpdate).replaceWith(res);
                });
            }
            //Post
            function LinkEdit(urlPath, targetUpdate, personId) {
                console.log('LinkEdit Url: ' + urlPath);
                $.post(urlPath,
                    {
                        Id: personId,
                        Name: $('#' + targetUpdate + 'Name').val(),
                        City: $('#' + targetUpdate + 'City').val(),
                        Phone: $('#' + targetUpdate + 'Phone').val()
                    },
                    function (res) {
                        $('#' + targetUpdate).replaceWith(res);
                    });
            }

            function LinkCreate(urlPath) {
                console.log('LinkCreate Url: ' + urlPath);
                $.post(urlPath,
                    {
                        name: $('#createName').val(),
                        city: $('#createCity').val(),
                        phone: $('#createPhone').val()
                    },
                    function (res) {
                        $('#AllPersons').append(res);
                    });
            }
            function LinkFilter(urlPath) {
                console.log('LinkCreate Url: ' + urlPath);
                $.post(urlPath,
                    {
                        filter: $('#filterlist').val(),//skappar nya list som ska sökas
                    },
                    function (res) {
                        $('#AllPersons').html(res);
                    });
            }
        </script>
    </body>
</html>